### ISSUE TITLE
请问您使用的word版本

### ISSUE THREAD

**Issue by user-tq** [pzweuj/WordWriter#1]
用您的测试文件及脚本，可以运行。
但是应该是兼容性问题，我用的word2016，插入新表后运行会报错（但是直接复制模板里的表又可以）。
```
ww.WordWriter("word2016test.docx", "word2016output.docx", resultsDict)
  File "g:\WordWriter-master\WordWriter-master\test\WordWriter.py", line 223, in WordWriter
    fillTable(i[0], i[1], i[2], replaceDict[k])
  File "g:\WordWriter-master\WordWriter-master\test\WordWriter.py", line 154, in fillTable
    r0 = p0.runs[0]
IndexError: list index out of range
```
另外也想请问下您有没有自动合并单元格的好办法

**Comment by pzweuj** [comment]
您可以试试将表格的标签所在的行的所有单元格都加入预设好格式的内容，随便填一个数字或其他。或者可以把您的输入文件发到我的[邮箱](mailto:pzweuj@live.com)，我测试一下。

[python-docx有合并单元格的功能](https://python-docx.readthedocs.io/en/latest/dev/analysis/features/table/cell-merge.html)，本来我打算加入到脚本中的，但是合并逻辑一直没调整好。可参考以下，将具有相同内容的单元格进行合并。
```python
import docx

def mergeFirstColumnCell(cell1, cell2):
    cell2.text.strip(cell2.text)
    cell1.merge(cell2)
```

**Comment by user-tq** [comment]
>
非常感谢，多有打扰
