### ISSUE TITLE
运行demo会报错

### ISSUE THREAD

**Issue by Swlymbcty** [pzweuj/WordWriter#2]
Traceback (most recent call last):
  File "...\WordWriter\test\Demo.py", line 20, in <module>
    ww.WordWriter("test.docx", "output.docx", resultsDict)
  File "...\WordWriter\test\WordWriter.py", line 346, in WordWriter
    fillTable(i[0], i[1], i[2], replaceDict[k])
  File "...\WordWriter\test\WordWriter.py", line 269, in fillTable
    tagBottomStyle, tagTableStyle = get_table_bottom_border_details(table, row_id, cell_id)
  File "...\WordWriter\test\WordWriter.py", line 95, in get_table_bottom_border_details
    tbl_bottom_border = tbl_borders.find(nsqn("w:bottom"))
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by pzweuj** [comment]
> Traceback (most recent call last): File "...\WordWriter\test\Demo.py", line 20, in ww.WordWriter("test.docx", "output.docx", resultsDict) File "...\WordWriter\test\WordWriter.py", line 346, in WordWriter fillTable(i[0], i[1], i[2], replaceDict[k]) File "...\WordWriter\test\WordWriter.py", line 269, in fillTable tagBottomStyle, tagTableStyle = get_table_bottom_border_details(table, row_id, cell_id) File "...\WordWriter\test\WordWriter.py", line 95, in get_table_bottom_border_details tbl_bottom_border = tbl_borders.find(nsqn("w:bottom")) AttributeError: 'NoneType' object has no attribute 'find'

感谢指正，请通过pip升级到3.1版本进行修复
```cmd
pip install --upgrade WordWriter
```
